# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Infinitive add-on
version: "1.1.1"
slug: infinitive
description: Infinitive
url: "https://github.com/tystuyfzand/ha-addons/tree/main/infinitive"
image: "ghcr.io/tystuyfzand/ha-addons-infinitive-{arch}"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
webui: "http://[HOST]:[PORT:8080]/"
options:
  serial_tty: null
  serial_addr: "localhost:1234"
schema:
  serial_tty: "device(subsystem=tty)?"
  serial_addr: "str?"
ports:
  8080/tcp: 8080
